### PR TITLE
Support ES6 re-export

### PR DESCRIPTION
**Pull request by SpainTrain**
* Update regex for js modules to support re-exporting (http://www.2ality.com/2014/09/es6-modules-final.html#re-exporting)

### CODE REVIEW

**Comment by SpainTrain** [comment]
e.g., 

```js
export * from './activity-selectors';
```

**Comment by SpainTrain** [comment]
ping: rebased on latest master

**Comment by nkt** [comment]
`export Foo from './bar'` this is not working

**Comment by SpainTrain** [comment]
That syntax isn't quite right for `export`, but yes my regex for variable names is definitely totally garbage `=-D` (http://stackoverflow.com/questions/1661197/what-characters-are-valid-for-javascript-variable-names).

I will fix it.  Since we probably do not want a 11,236 characters long regex, I will use some reasonable subset of the valid characters :grin:

**Comment by SpainTrain** [comment]
Ok, this version works on all the following cases, which I think should cover most reasonable cases (crazy unicode identifiers aside):

```
export * from 'src/other_module';

export { foo, bar } from 'src/other_module';
export { FOO, bar1 } from 'src/other_module';
export { FOO_BAR, bar } from 'src/other_module';
export { FOO_BAR, $bar } from 'src/other_module';
    
// Export other_module’s foo as myFoo
export { $foo as myFoo, bar } from 'src/other_module';
export { f00 as myFoo, bar } from 'src/other_module';
export { FOO as myFoo, bar } from 'src/other_module';
export { FOO_BAR as myFoo, bar } from 'src/other_module';
```

**Comment by nkt** [comment]
Great, thanks

**Comment by SpainTrain** [comment]
Thanks for pointing out the godawful regex =-D

**Pull request merged**
