### PR TITLE
Fix babel module resolver support

### PR DESCRIPTION
**Pull request by nicolaslopezj**
The old way never worked for me. This new code is tested and it works

### CODE REVIEW

**Comment by jhicken** [comment]
#53 is probably a duplicate of this

**Comment by jhicken** [comment]
However this does not support the regex stuff that is in babel-plugin-module-resolver.  It would really be fantastic if babel-plugin-module-resolver export some utility functions that we would use. I looked into this for a min but it looks like there getRealName module would need some customization.

**Comment by jonyeezs** [comment]
@nicolaslopezj, @jhicken mentioned that this is a duplicate of another PR.

His doesn't have any conflicts (ie: easier to merge).

Does #53 work for you too @nicolaslopezj?

**Comment by jonyeezs** [comment]
Closing this PR, as there has been no response for awhile. And any active maintainer is clueless about this.

Please reply here anyone if you can answer any questions above.

**Pull request closed without merging**
