### PR TITLE
Added basic support for TypeScript

### PR DESCRIPTION
**Pull request by bromzh**

### CODE REVIEW

**Comment by nkt** [comment]
Thanks, but I added it manually.

**Comment by bromzh** [comment]
Thank you! But when I choose suggestion with suffix `.ts`, it remains in result. May be add `.ts` into regexp in [here](https://github.com/nkt/atom-autocomplete-modules/blob/master/src/completion-provider.js#L110)?

**Comment by nkt** [comment]
@bromzh yes, I forgot this. Added in **1.5.1**

**Comment by bromzh** [comment]
@nkt Nice, thanks a lot!

**Pull request closed without merging**
